---
deployment:
  tasks:
    - export REPO_PATH=/home/wartegja/repositories/wartol
    - export DEPLOY_PATH=/home/wartegja/wartegja.my.id/public_html

    # Sync file ke public_html
    - /bin/rsync -av --delete --exclude='.git' $REPO_PATH/ $DEPLOY_PATH/

    - /usr/local/bin/php $DEPLOY_PATH/artisan config:clear
    - /usr/local/bin/php $DEPLOY_PATH/artisan cache:clear
    - /usr/local/bin/php $DEPLOY_PATH/artisan config:cache
    - /usr/local/bin/php $DEPLOY_PATH/artisan route:cache
    - /usr/local/bin/php $DEPLOY_PATH/artisan view:cache
